apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  appInstanceLabelKey: app.kubernetes.io/name
  image.repository: "docker.io/ivandomingues/ivan-teste"
  image.tagPolicy: "latest"  # Ou use um formato específico de tag
  image.updateStrategy: "automated"
