name: Docker Build and Push

on:
  push:
    paths:
      - teste_site_web/**  # Verifica qualquer alteração no diretório "teste_site_web" ou seus subdiretórios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Adicione suas credenciais no GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ivandomingues/ivan-teste:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ivandomingues/ivan-teste:latest

    - name: Trigger ArgoCD sync (Git commit)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git clone https://github.com/ivandomingues/argocd-repo.git  # Clonar o repositório monitorado pelo ArgoCD
        cd kubernetes
        # Atualize um arquivo no diretório monitorado, como um arquivo de "marca" ou manifestos
        echo "Atualizando imagem Docker para a tag latest" > monitora.txt
        git add .
        git commit -m "Atualização da imagem Docker para a tag latest"
        git push
