# name: Docker Build and Push

# on:
#   push:
#     paths:
#       - teste_site_web/**  # Verifica qualquer alteração no diretório "teste_site_web" ou seus subdiretórios

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}  # Adicione suas credenciais no GitHub Secrets
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build Docker image
#       run: |
#         docker build -t ivandomingues/ivan-teste:latest .

#     - name: Push Docker image to Docker Hub
#       run: |
#         docker push ivandomingues/ivan-teste:latest

name: Docker Build and Push

on:
  push:
    paths:
      - teste_site_web/**  # Verifica qualquer alteração no diretório "teste_site_web" ou seus subdiretórios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Adicione suas credenciais no GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the latest version tag (local increment)
      id: get_latest_tag
      run: |
        latest_tag= 1
        #latest_version_number=$(echo $latest_tag | sed 's/v\([0-9]\+\)/\1/')
        next_version=$((latest_tag + 1))
        export next_version
        # latest_tag="v$next_version"

    - name: Build Docker image
      run: |
        docker build -t ivandomingues/ivan-teste:v$next_version .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ivandomingues/ivan-teste:v$next_version

    - name: Write to monitor.txt
      run: |
        echo "Imagem ivandomingues/ivan-teste:v$next_version foi atualizada em $(date)" >> kubernetes/monitor.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necessário para escrita no repositório

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Pipe codou fofamente por versão!
