name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Ou outro branch desejado
    paths:
      - 'teste_site_web/**'  # Apenas mudanças nesse arquivo vão disparar a pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar credenciais Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Senha ou token de acesso do Docker Hub

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Construir imagem Docker
      run: |
        docker buildx build -t docker build -t ${{ secrets.DOCKER_USERNAME }}/ivan-teste:latest .


    - name: Criar tag para a imagem
      run: |
        docker tag docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/ivan-teste:latest

    - name: Enviar imagem para o Docker Hub
      run: |
        docker push docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/ivan-teste:latest

    - name: Limpeza
      run: |
        docker rmi docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/ivan-teste:latest

