name: Build and Push Docker Image to GitLab Container Registry

on:
  push:
    branches:
      - main  # Dispara a pipeline apenas em mudanças na branch main
    paths:
      - 'teste_site_web/**'  # Apenas mudanças nesse diretório disparam a pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    
    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Construir e enviar imagem Docker para o GitLab Container Registry
      run: |
        docker buildx build -t https://gitlab.com/ivan.domingues1/testes-deploy.git:latest --push .

    - name: Limpeza (opcional)
      run: docker rmi https://gitlab.com/ivan.domingues1/testes-deploy.git:latest
