name: Docker Build and Push

on:
  push:
    paths:
      - teste_site_web       # Ou qualquer arquivo específico para monitorar mudanças
  # pull_request:
  #   paths:
  #     - Dockerfile
  #     - '**/*.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Adicione suas credenciais no GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ivandomingues/ivan-teste:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ivandomingues/ivan-teste:latest
