name: Docker Build and Push

on:
  push:
    paths:
      - teste_site_web/**  # Verifica qualquer alteração no diretório "teste_site_web" ou seus subdiretórios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Adicione suas credenciais no GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ivandomingues/ivan-teste:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ivandomingues/ivan-teste:latest

    - name: Update monitor.txt with incremental comment
      run: |
        git clone https://github.com/***/argocd-repo.git  # Clonar o repositório monitorado pelo ArgoCD
        cd argocd-repo/kubernetes
        # Incrementar a data/hora ou alguma outra informação relevante
        echo "Imagem Docker 'ivan-teste:latest' empurrada para o Docker Hub em $(date)" >> monitor.txt
        git add monitor.txt
        git commit -m "Incremental update no monitor.txt após o push da imagem Docker"
        git push
      shell: bash
