name: Push the Docker image to AWS ECR Repo and deploy to EKS
on:
  push:
    branches:
      - pipe

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: app

permissions:
   id-token: write
   contents: read

jobs:
  Build-and-Deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      
      - name: Image tag definition
        id: tag
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.branch.outputs.branch }}-v${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          provenance: false
          tags: ${{ steps.tag.outputs.image }}    